### PR TITLE
[BISERVER-13099] - Fix XTRE0540 Ambiguous rule match

### PR DESCRIPTION
**Pull request by petrprochy**

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  package-res/WEB-INF/jpivot/navi/navigator.xsl

**Comment by petrprochy** [comment]
Result of called build command is BUILD SUCCESSFUL. What is problem with this patch?

**Comment by lucboudreau** [comment]
Nobody said there was a problem. The patch is not merged simply because the Jira ticket associated to it is not scheduled for a release.

**Comment by petrprochy** [comment]
Aha :), I thought that problem is in violation of checkstyle or something else.

**Pull request merged**
