### PR TITLE
fix Open input stream of template file never closed

### PR DESCRIPTION
**Pull request by petrprochy**
HTML template is reader from input stream via BufferedReader but this stream is never closed.

### CODE REVIEW

**Comment by pamval** [comment]
@petrprochy please create a jira describing the issue at jira.pentaho.com. All pull requests require a jira to be created.

**Comment by petrprochy** [comment]
OK, created issue is http://jira.pentaho.com/browse/BISERVER-13066

**Comment by akhayrutdinov** [comment]
@petrprochy, can you please reword the commit's name so, that it becomes similar to others?
Namely, yours can be such:
 ```
[BISERVER-13066] - JPivot plugin - Open input stream in reading template file
- fix Open input stream of template file never closed
```

**Comment by petrprochy** [comment]
Yes, of course. It's not problem :).

**Comment by akhayrutdinov** [comment]
@petrprochy, I see a merge commit in this PR. Could you please eliminate it by using `rebase` operation against the repository's master branch? Thanks.

**Comment by petrprochy** [comment]
oh, I do some think wrong. Is any chance to reopen of pull? Or I have to create new one.

**Comment by akhayrutdinov** [comment]
@petrprochy, I think it is easier to create another PR

**Pull request closed without merging**
